export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_USER = 'ADD_USER'
export const USER_LIST = 'USERS_LIST'

export const HANDLE_NEW_MESSAGE_REQUEST = 'HANDLE_NEW_MESSAGE_REQUEST'
export const HANDLE_NEW_MESSAGE_SUCCESS = 'HANDLE_NEW_MESSAGE_REQUEST'
